import type { NextPage } from "next";
import Head from "next/head";
import { Blogs as BlogsPage } from "../components/Blogs/Blogs";

const Blogs: NextPage = () => {
    return (
        <div>
            <Head>
                <title>omkathe | blogs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BlogsPage />
        </div>
    );
};

export default Blogs;
