import type { NextPage } from "next";
import Head from "next/head";
import { Experience as ExperiencePage } from "@components/Experience/Experience";

const Experience: NextPage = () => {
    return (
        <div>
            <Head>
                <title>omkathe | experience</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ExperiencePage />
        </div>
    );
};

export default Experience;
