import type { NextPage } from "next";
import Head from "next/head";
import { Home as HomePage } from "@components/Home/Home";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>omkathe | home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomePage />
        </div>
    );
};

export default Home;
