import type { NextPage } from "next";
import Head from "next/head";
import { Home as HomePage } from "@components/Home/Home";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>omkathe | home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"/>
            </Head>
            <HomePage/>
        </div>
    );
};

export default Home;
